#!/usr/bin/php
<?php
	
	namespace CLI;

	/*************************
	 *                       *
	 *   (C)Copyright 2013   *
	 *     Niels Fyhring     *
	 *                       *
	 *************************/


	error_reporting(E_ALL);
	ini_set('display_errors', 1);



	$cli 	= true;
	require_once('paths.php');


	require_once(SYS .'cli/hydrogen.php');
	
	Hydrogen::input( $_SERVER['argv'] );

	try {
		Hydrogen::run_command();
	}
	catch(CLIException $e) {
		die($e);
	}
	
	